name: Build MegaLinter Custom Flavor

on:
  push:
  release:
    types: [ created, edited, published ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-custom-flavor:
    name: Build Custom MegaLinter Flavor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Log in to Docker Hub only if credentials are provided
      - name: Log in to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build MegaLinter Custom Flavor
        uses: oxsecurity/megalinter/flavors/custom-builder@alpha
        with:
          megalinter-custom-flavor-builder-tag: ${{ github.event_name == 'release' && github.event.release.tag_name || 'alpha' }}
          is-latest: ${{ github.event_name == 'release' && 'true' || 'false' }}
          upload-to-ghcr: "true"
          upload-to-dockerhub: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' && 'true' || 'false' }}
          dockerhub-repo: "nvuillam"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_FLAVOR_BUILD_REPO: ${{ github.repository }}
          CUSTOM_FLAVOR_BUILD_REPO_URL: ${{ github.repositoryUrl }}
          CUSTOM_FLAVOR_BUILD_USER: ${{ github.actor }}

